<?php

namespace App\Imports;

use App\Models\Device;
use App\Models\DeviceInterface;
use App\Models\Vendor;
use App\Models\DeviceCategory;
use App\Models\OperatingSystem;
use Illuminate\Support\Facades\Log;

/**
 * Import a single-device MikroTik audit Excel file.
 *
 * Expected sheet structure:
 *   - "Ringkasan Perangkat": key-value pairs (A=Parameter, B=Nilai)
 *   - "Interface": rows of interface data starting at row 2
 *   - "IP Address": rows of IP data starting at row 2
 *
 * These files are generated by the CIMS MikroTik audit tool and contain
 * inline strings (no sharedStrings.xml).
 */
class SingleDeviceAuditImport
{
    /**
     * Shared string table of the workbook being parsed.
     * Empty for the audit tool's own files, which use inline strings; populated
     * when the file has been re-saved by Excel/LibreOffice.
     *
     * @var string[]
     */
    private array $sharedStrings = [];

    /**
     * List the worksheet names inside an .xlsx file.
     *
     * @param string $filePath Absolute path to the .xlsx file
     * @return string[] Empty when the file is missing or unreadable
     */
    public static function sheetNames(string $filePath): array
    {
        try {
            $z = new \ZipArchive();
            if ($z->open($filePath) !== true) {
                return [];
            }

            $wbXml = $z->getFromName('xl/workbook.xml');
            $z->close();

            return $wbXml === false ? [] : self::getSheetNames($wbXml);
        } catch (\Throwable $e) {
            Log::error("SingleDeviceAuditImport::sheetNames error: " . $e->getMessage());
            return [];
        }
    }

    /**
     * Detect whether an Excel file matches the single-device audit format.
     *
     * @param string $filePath Absolute path to the .xlsx file
     * @return bool
     */
    public static function canHandle(string $filePath): bool
    {
        $sheetNames = self::sheetNames($filePath);

        // This format has "Ringkasan Perangkat" and "Interface" sheets
        return in_array('Ringkasan Perangkat', $sheetNames, true)
            && in_array('Interface', $sheetNames, true);
    }

    /**
     * Import the device and its interfaces from the audit Excel file.
     *
     * @param string $filePath Absolute path to the .xlsx file
     * @return Device|null
     */
    public function import(string $filePath): ?Device
    {
        $z = new \ZipArchive();
        if ($z->open($filePath) !== true) {
            Log::error("SingleDeviceAuditImport: cannot open {$filePath}");
            return null;
        }

        // Resolve sheet paths from workbook relationships
        $sheetPaths = $this->resolveSheetPaths($z);

        // Files re-saved by Excel move their text into a shared string table
        $this->sharedStrings = $this->loadSharedStrings($z);

        // 1. Parse "Ringkasan Perangkat" (device summary)
        $summary = $this->parseSummarySheet($z, $sheetPaths['Ringkasan Perangkat'] ?? null);
        if (empty($summary)) {
            $z->close();
            Log::warning("SingleDeviceAuditImport: empty summary sheet");
            return null;
        }

        // 2. Parse "Interface" sheet
        $interfaces = $this->parseInterfaceSheet($z, $sheetPaths['Interface'] ?? null);

        // 3. Parse "IP Address" sheet (optional, for enrichment)
        $ipAddresses = $this->parseIpAddressSheet($z, $sheetPaths['IP Address'] ?? null);

        $z->close();

        // Build device record
        $deviceName = $this->buildDeviceName($summary, $filePath);
        $ipAddress  = $summary['Host / IP Router'] ?? null;
        $board      = $summary['Board'] ?? null;
        $firmware   = $summary['Versi Software (Patch)'] ?? null;
        $serialNum  = $summary['Serial Number (SN)'] ?? null;
        $username   = $summary['Username'] ?? null;
        $password   = $summary['Password'] ?? null;
        $merek      = $summary['Merek'] ?? 'MikroTik';

        // Resolve vendor
        $vendor = Vendor::firstOrCreate(
            ['name' => $merek],
            ['contact_person' => 'Support', 'email' => 'support@' . strtolower(str_replace(' ', '', $merek)) . '.com']
        );

        // Resolve category
        $category = DeviceCategory::firstOrCreate(
            ['name' => 'Router'],
            ['description' => 'Networking Router Devices']
        );

        // Resolve operating system
        $os = null;
        if ($firmware) {
            $os = OperatingSystem::firstOrCreate(
                ['name' => 'RouterOS'],
                ['vendor' => 'MikroTik', 'version' => $firmware]
            );
        }

        // Determine match key: serial number -> IP -> device name
        if ($serialNum) {
            $matchKey = ['serial_number' => $serialNum];
        } elseif ($ipAddress) {
            $matchKey = ['ip_address' => $ipAddress];
        } else {
            $matchKey = ['name' => $deviceName];
        }

        $device = Device::updateOrCreate(
            $matchKey,
            [
                'name'               => $deviceName,
                'hostname'           => $board ? "{$board}" : $deviceName,
                'ip_address'         => $ipAddress,
                'vendor_id'          => $vendor->id,
                'device_category_id' => $category->id,
                'operating_system_id' => $os?->id,
                'model'              => $board,
                'serial_number'      => $serialNum,
                'firmware'           => $firmware,
                'username'           => $username,
                'password_encrypted' => $password ? encrypt($password) : null,
                'status'             => 'active',
                'source'             => 'inventory',
            ]
        );

        // Import interfaces
        if (!empty($interfaces)) {
            foreach ($interfaces as $iface) {
                $ifaceName = $iface['name'] ?? null;
                if (!$ifaceName) continue;

                // Merge IP data from the IP Address sheet
                $ipData = $ipAddresses[$ifaceName] ?? [];
                $ipAddr = $iface['ip'] ?? $ipData['ip'] ?? null;
                $subnet = null;

                // Parse CIDR notation (e.g. "192.168.91.1/24")
                if ($ipAddr && str_contains($ipAddr, '/')) {
                    [$ipAddr, $prefix] = explode('/', $ipAddr, 2);
                    $subnet = $this->cidrToSubnet((int)$prefix);
                }

                DeviceInterface::updateOrCreate(
                    [
                        'device_id'      => $device->id,
                        'interface_name' => $ifaceName,
                    ],
                    [
                        'ip_address'       => ($ipAddr && $ipAddr !== '-') ? $ipAddr : null,
                        'subnet'           => $subnet,
                        'mac_address'      => ($iface['mac'] ?? null) !== '00:00:00:00:00:00' ? ($iface['mac'] ?? null) : null,
                        'interface_type'   => $this->mapInterfaceType($iface['type'] ?? ''),
                        'interface_status' => $this->mapStatus($iface['status'] ?? ''),
                        'mtu'              => isset($iface['mtu']) && is_numeric($iface['mtu']) ? (int)$iface['mtu'] : null,
                        'description'      => $iface['comment'] ?? null,
                    ]
                );
            }
        }

        Log::info("SingleDeviceAuditImport: imported device '{$device->name}' with " . count($interfaces) . " interfaces");
        return $device;
    }

    // ─── Private helpers ───────────────────────────────────────────

    private function resolveSheetPaths(\ZipArchive $z): array
    {
        $wbXml = $z->getFromName('xl/workbook.xml');
        $relsXml = $z->getFromName('xl/_rels/workbook.xml.rels');

        $ns = 'http://schemas.openxmlformats.org/spreadsheetml/2006/main';
        $nsRel = 'http://schemas.openxmlformats.org/package/2006/relationships';

        $wb = new \SimpleXMLElement($wbXml);
        $wb->registerXPathNamespace('m', $ns);
        $rels = new \SimpleXMLElement($relsXml);
        $rels->registerXPathNamespace('r', $nsRel);

        // Build rId -> target map
        $relMap = [];
        foreach ($rels->xpath('//r:Relationship') as $rel) {
            $relMap[(string)$rel['Id']] = (string)$rel['Target'];
        }

        $result = [];
        $nsR = 'http://schemas.openxmlformats.org/officeDocument/2006/relationships';
        foreach ($wb->xpath('//m:sheet') as $sheet) {
            $name = (string)$sheet['name'];
            $rId  = (string)$sheet->attributes($nsR)['id'];
            $target = $relMap[$rId] ?? null;
            if ($target) {
                // Normalize path
                if (str_starts_with($target, '/')) {
                    $result[$name] = ltrim($target, '/');
                } elseif (!str_starts_with($target, 'xl/')) {
                    $result[$name] = 'xl/' . $target;
                } else {
                    $result[$name] = $target;
                }
            }
        }

        return $result;
    }

    private function parseSummarySheet(\ZipArchive $z, ?string $path): array
    {
        if (!$path) return [];

        $xml = $z->getFromName($path);
        if ($xml === false) return [];

        $rows = $this->parseSheetRows($xml);
        $summary = [];

        foreach ($rows as $row) {
            $key = $row['A'] ?? null;
            $val = $row['B'] ?? null;
            if ($key && $val && $key !== 'Parameter') {
                $summary[$key] = $val;
            }
        }

        return $summary;
    }

    private function parseInterfaceSheet(\ZipArchive $z, ?string $path): array
    {
        if (!$path) return [];

        $xml = $z->getFromName($path);
        if ($xml === false) return [];

        $rows = $this->parseSheetRows($xml);
        $interfaces = [];

        foreach ($rows as $idx => $row) {
            // Skip header row
            if (($row['A'] ?? '') === 'Nama Interface') continue;

            $name = $row['A'] ?? null;
            if (!$name) continue;

            $interfaces[] = [
                'name'    => $name,
                'type'    => $row['B'] ?? '',
                'mac'     => $row['C'] ?? null,
                'status'  => $row['D'] ?? '',
                'bridge'  => $row['E'] ?? null,
                'mtu'     => $row['F'] ?? null,
                'ip'      => $row['H'] ?? null,
                'comment' => $row['J'] ?? null,
            ];
        }

        return $interfaces;
    }

    private function parseIpAddressSheet(\ZipArchive $z, ?string $path): array
    {
        if (!$path) return [];

        $xml = $z->getFromName($path);
        if ($xml === false) return [];

        $rows = $this->parseSheetRows($xml);
        $result = [];

        foreach ($rows as $row) {
            if (($row['A'] ?? '') === 'Interface') continue;

            $ifName = $row['A'] ?? null;
            if (!$ifName) continue;

            $result[$ifName] = [
                'ip'      => $row['B'] ?? null,
                'network' => $row['C'] ?? null,
                'type'    => $row['D'] ?? null,
            ];
        }

        return $result;
    }

    /**
     * Read xl/sharedStrings.xml into an index-ordered list of plain strings.
     *
     * @return string[]
     */
    private function loadSharedStrings(\ZipArchive $z): array
    {
        $xml = $z->getFromName('xl/sharedStrings.xml');
        if ($xml === false) {
            return [];
        }

        $ns = 'http://schemas.openxmlformats.org/spreadsheetml/2006/main';
        $doc = new \SimpleXMLElement($xml);
        $doc->registerXPathNamespace('m', $ns);

        $strings = [];
        foreach ($doc->xpath('//m:si') as $si) {
            $si->registerXPathNamespace('m', $ns);

            // An <si> is either one <t>, or several <r><t> runs that concatenate
            $text = '';
            foreach ($si->xpath('.//m:t') as $t) {
                $text .= (string)$t;
            }
            $strings[] = $text;
        }

        return $strings;
    }

    /**
     * Parse all rows from a worksheet XML, handling both shared strings and inline strings.
     */
    private function parseSheetRows(string $xml): array
    {
        $ns = 'http://schemas.openxmlformats.org/spreadsheetml/2006/main';

        $doc = new \SimpleXMLElement($xml);
        $doc->registerXPathNamespace('m', $ns);

        $rows = [];
        foreach ($doc->xpath('//m:sheetData/m:row') as $row) {
            // Re-register namespace on child element (SimpleXML quirk)
            $row->registerXPathNamespace('m', $ns);

            $cols = [];
            foreach ($row->xpath('m:c') as $cell) {
                $cell->registerXPathNamespace('m', $ns);

                $ref = (string)$cell['r'];
                $colLetter = preg_replace('/[0-9]/', '', $ref);
                $type = (string)$cell['t'];

                // Inline string
                $isElem = $cell->xpath('m:is//m:t');
                if (!empty($isElem)) {
                    $val = '';
                    foreach ($isElem as $t) {
                        $val .= (string)$t;
                    }
                } else {
                    $vElem = $cell->xpath('m:v');
                    $val = !empty($vElem) ? (string)$vElem[0] : '';

                    // t="s": <v> holds an index into the shared string table
                    if ($type === 's' && $val !== '' && isset($this->sharedStrings[(int)$val])) {
                        $val = $this->sharedStrings[(int)$val];
                    }
                }

                if (trim($val) !== '') {
                    $cols[$colLetter] = trim($val);
                }
            }

            if (!empty($cols)) {
                $rows[] = $cols;
            }
        }

        return $rows;
    }

    private static function getSheetNames(string $wbXml): array
    {
        $ns = 'http://schemas.openxmlformats.org/spreadsheetml/2006/main';
        $doc = new \SimpleXMLElement($wbXml);
        $doc->registerXPathNamespace('m', $ns);

        $names = [];
        foreach ($doc->xpath('//m:sheet') as $sheet) {
            $names[] = (string)$sheet['name'];
        }

        return $names;
    }

    private function buildDeviceName(array $summary, string $filePath): string
    {
        $board = $summary['Board'] ?? '';
        $ip    = $summary['Host / IP Router'] ?? '';

        if ($board && $ip) {
            return "MikroTik_{$board}_{$ip}";
        }

        // Fallback to filename
        $basename = pathinfo($filePath, PATHINFO_FILENAME);
        return str_replace(['_', '-'], ' ', $basename);
    }

    private function mapInterfaceType(string $type): string
    {
        return match (strtolower($type)) {
            'ether', 'ethernet' => 'ethernet',
            'bridge'            => 'bridge',
            'vlan'              => 'vlan',
            'loopback'          => 'loopback',
            'pppoe-out', 'ppp'  => 'ppp',
            'wireless', 'wlan'  => 'wireless',
            default             => 'other',
        };
    }

    private function mapStatus(string $status): string
    {
        return match (strtolower($status)) {
            'running', 'up', 'aktif' => 'up',
            default                  => 'down',
        };
    }

    private function cidrToSubnet(int $prefix): string
    {
        $mask = ($prefix > 0) ? (~0 << (32 - $prefix)) : 0;
        return long2ip($mask & 0xFFFFFFFF);
    }
}
